### ISSUE TITLE
Can't sign up because of Firebase error on notational.co

### ISSUE THREAD

**Issue by andreiglingeanu** [tmm/notational#1]
[Screenshot](https://cl.ly/kUkl)

Don't know what is the problem there, pretty sure I inserted a valid email address.

**Comment by tmm** [comment]
@andreiglingeanu Just pushed the fix! The email is valid – it was passed to Firebase the wrong way. Thanks for bringing this up!

**Comment by andreiglingeanu** [comment]
Awesome! The app looks very nice!

**Comment by tmm** [comment]
Thanks! Feel free to contribute or request features!
