### ISSUE TITLE
Problem with hosting

### ISSUE THREAD

**Issue by snthcy** [tmm/notational#11]
Hello! I am trying to self host your project. I made a settings.js and put the required things inside of it,
I enabled authentication as email/password, I enabled hosting but I want to work in local host till it works, I need help with the database and storage, as I do not know how to set it up. When I signed up on the local host, it let me sign up, but it was in an infinite loop at localhost:8080/app.
Here is a screenshot of the authentication:
[https://file.coffee/2kEamL0V5.png](https://file.coffee/2kEamL0V5.png)

**Comment by tmm** [comment]
Have you set up a [Realtime Database](https://firebase.google.com/docs/database) instance?

If so, you need to add a `default_notes` key to the root with an object value:

```
  "default_notes" : {
    "notes" : [
	    {
	      "body" : "The quick brown fox jumped over the lazy dogs.",
	      "date_created" : "Sun Mar 05 2017 18:15:27 GMT-0500",
	      "date_modified" : "Sun Mar 05 2017 18:25:02 GMT-0500",
	      "id" : 1,
	      "name" : "Welcome (Click Me)"
	    },
	    ...
    ]
  },
```

**Comment by snthcy** [comment]
> Have you set up a [Realtime Database](https://firebase.google.com/docs/database) instance?
> 
> If so, you need to add a `default_notes` key to the root with an object value:
> 
> ```
>   "default_notes" : {
>     "notes" : [
> 	    {
> 	      "body" : "The quick brown fox jumped over the lazy dogs.",
> 	      "date_created" : "Sun Mar 05 2017 18:15:27 GMT-0500",
> 	      "date_modified" : "Sun Mar 05 2017 18:25:02 GMT-0500",
> 	      "id" : 1,
> 	      "name" : "Welcome (Click Me)"
> 	    },
> 	    ...
>     ]
>   },
> ```

is this in the rules tab?

**Comment by tmm** [comment]
that should go under the `Data` tab:

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/6759464/72445835-5d5dee80-3780-11ea-8d88-efd4b6ed347e.png">

Rules should be this:

```
{
  "rules": {
    "default_notes": {
      ".read": true,
      ".write": false
    },
    "public_notes": {
      ".read": true,
      ".write": "auth != null"
    },
    "users": {
      "$uid": {
        ".read": "$uid === auth.uid",
        ".write": "$uid === auth.uid",
        "notes": {
          "$id": {
            ".read": "data.child('is_public').val() == true"
          }
        }
      }
    }
  }
}
```

**Comment by snthcy** [comment]
![image](https://user-images.githubusercontent.com/47870580/72446908-68b21980-3782-11ea-8ea8-392d1574a831.png)
![image](https://user-images.githubusercontent.com/47870580/72446933-71a2eb00-3782-11ea-8ece-80165e61b70c.png)

Looks good? If so I will get back to you if it works :)

**Comment by tmm** [comment]
Yup, let me know if that does the trick.

**Comment by snthcy** [comment]
It works! At first I was getting an error, but it was because I forgot to make the settings.js file. Thanks for your help!

**Comment by snthcy** [comment]
I forgot to ask. Can you help me with hosting it on firebase? When I do firebase init and firebase deploy it just shows this
![image](https://user-images.githubusercontent.com/47870580/72469029-885e3780-37ac-11ea-9403-f297af0a09e8.png)

**Comment by tmm** [comment]
Did you go through the set up under `Develop > Hosting > Get Started`? If so, what does the `Dashboard` section look like? Should be something like this:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/6759464/72469226-fd317180-37ac-11ea-8402-0a231ecd7783.png">

Note: You also have to run `npm run build` before you deploy.

**Comment by snthcy** [comment]
I did everything you said.

**Comment by snthcy** [comment]
![image](https://user-images.githubusercontent.com/47870580/72469416-58636400-37ad-11ea-9968-ea0556e47433.png)
Oh, should i worry if someone gets my firebase project name?

**Comment by tmm** [comment]
I wouldn't worry about the name. Is it working now? Looks like there is a deploy.

If not, drop me an email. Will be faster to get you up and running.
