### ISSUE TITLE
Project attribution

### ISSUE THREAD

**Issue by scrod** [tmm/notational#2]
Hi Tom,

Based on the way your project is described, it's possible to assume that it is either part of, or associated with, the Notational Velocity project.

Please change your project description to explicitly state that your project is not affiliated with Notational Velocity in any way. Even calling it "Notational" is confusing enough, given the similarity of the interface.

Regards,

Zachary Schneirov

**Comment by tmm** [comment]
Hi @scrod, I've updated the description to:

> Notational Velocity-inspired web app built with Vue.js (Not affiliated with Notational Velocity in any way)

Let me know if that is sufficient. Also, will add the same text to the top of the `README.md` and the footer of the home page, along with a link to [notational.net](http://notational.net/).

**Comment by scrod** [comment]
Thanks, Tom, that sounds great.
