### ISSUE TITLE
Minimal local development setup

### ISSUE THREAD

**Issue by RobertBolender** [tmm/notational#3]
Fantastic live demo!

I just tried to clone the project and run it locally, and I've run into a few things:

    Module not found: Error: Can't resolve '../../settings' in '/home/bob/projects/personal/notational/src/store'

There needs to be some settings.json (or settings.js?) in the project root, but that is ignored by git and there is no sample file.

Could you please add a sample of the minimal settings file needed to get this up and running locally?

I'm not familiar with Firebase, will I need to sign up for it to run this project locally?

**Comment by RobertBolender** [comment]
I managed to get this working locally.
I signed up for a Firebase account and created a new project. It presented me with configuration options for integrating with a web app. I pasted these into a `settings.js` file in the project root, looking something like this:

```
ENV = {
  firebase: {
    apiKey: "",
    authDomain: "",
    databaseURL: "",
    projectId: "",
    storageBucket: "",
    messagingSenderId: ""
  }
};
```

I had to enable the Firebase email/password authentication provider.
I also had to add an entry to the database to prevent a JS error in the app:

```
key: default_notes
value: notes
```

I'm still getting a 404 on /styles.css, but otherwise the app seems to be working well!

**Comment by cdock1029** [comment]
For future reference, after creating a firebase app you can find this config data at:

[Firebase Console](https://console.firebase.google.com) 
- click Your-firebase-project-name  
- Authentication tab 
- top right button "Web Setup"

**Comment by tmm** [comment]
@awesomebob great point! I will add this to the `README.md` so others can benefit.

**Comment by junjie-xyz** [comment]
Do I need to paste the database.rules.json file on firebase's Database->Rules config tab? Actually, after doing so, the error 'permission_denied at /default_notes/notes' disappeared from my console.
![image](https://cloud.githubusercontent.com/assets/8137136/26434064/fac6d3e4-4138-11e7-8714-edfd496d214c.png)
