### ISSUE TITLE
Wrap as electron app?

### ISSUE THREAD

**Issue by cheapsteak** [tmm/notational#4]

**Comment by tmm** [comment]
Thanks for the feedback! Here's my [comment from Product Hunt](https://www.producthunt.com/posts/notational#comment-473562) earlier today:

> ... No native app planned right now -- I don't have time to focus on it and don't want to slap something together in Electron. This needs to be a true native app for the experience to be good.

If you are on macOS, you can check out [Notational Velocity](https://github.com/scrod/nv). NV is amazing and inspired Notational. If there is a burning need for Electron, someone is welcome to create it and I'll link to it (Notational is under the MIT license).
