### ISSUE TITLE
Add social signup to avoid creating more passwords

### ISSUE THREAD

**Issue by cdock1029** [tmm/notational#5]
Can use this library, dead simple.. 

https://github.com/firebase/firebaseui-web

**Comment by tmm** [comment]
@cdock1029 Good idea! I considered using social auth, but decided to go with email for now. (I guess this would cut down on the number of fake email addresses.)

Anyway, I'm going to close this until I have more time and other features are complete. If this is a burning need for a lot of people, I will open it up again. (That said, Notational is open source so feel free to jump in and add it yourself!)
