### ISSUE TITLE
Cant create new notes

### ISSUE THREAD

**Issue by cdock1029** [tmm/notational#6]
Some how I got my data into an broken state, and creating new notes (ctl + enter) fails:

```
Uncaught (in promise) Error: Firebase.push failed: first argument contains NaN in property 'users.TEUg6M4xcTTO6rtrUBzNVIWanqt2.notes.id'
    at Pd (build.js:43)
    at build.js:43
    at fb (build.js:43)
    at Pd (build.js:43)
    at Od (build.js:43)
    at U.g.push (build.js:43)
    at build.js:14
    at Promise (<anonymous>)
    at Object.createNote (build.js:14)
    at CREATE_NOTE (build.js:14)
````

Also I have 2 zombie notes showing up that cant be deleted...

<img width="884" alt="screen shot 2017-05-24 at 4 07 22 pm" src="https://cloud.githubusercontent.com/assets/802586/26423503/e4c023fe-409b-11e7-9da7-ddb179c0dbdc.png">

Cool project and great UI by the way...

**Comment by tmm** [comment]
@cdock1029 Wow! That doesn't look good. Thanks for reporting.

In the meantime, what's your email address? I can fix your account so it isn't broken anymore.
